import raw from './catalog.json';
import type { Catalog, CatalogModel, CatalogPackage } from './types.ts';

export type * from './types.ts';

/** The static catalog, generated by `pnpm catalog:generate` and committed. */
export const catalog = raw as unknown as Catalog;

const byId = new Map(catalog.packages.map((pkg) => [pkg.id, pkg]));

export function getPackage(id: string): CatalogPackage | undefined {
  return byId.get(id);
}

export function getModel(
  packageId: string,
  modelName: string,
): CatalogModel | undefined {
  return byId.get(packageId)?.models.find((m) => m.name === modelName);
}

/** The models of a package that get generated views (and nav entries). */
export function exposedModels(pkg: CatalogPackage): CatalogModel[] {
  return pkg.models.filter((m) => m.exposed);
}

/** Case-insensitive match on package id, description, model and field names. */
export function searchPackages(
  packages: readonly CatalogPackage[],
  query: string,
): CatalogPackage[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [...packages];
  return packages.filter((pkg) => {
    const haystack = [
      pkg.id,
      pkg.description,
      ...pkg.models.flatMap((m) => [
        m.name,
        m.collection,
        ...m.fields.map((f) => f.name),
      ]),
    ]
      .join(' ')
      .toLowerCase();
    return terms.every((term) => haystack.includes(term));
  });
}

/** Total number of generated surfaces (REST + MCP + CLI) for a package. */
export function surfaceCount(pkg: CatalogPackage): number {
  return pkg.models.reduce(
    (sum, m) => sum + m.rest.length + m.mcp.length + m.cli.length,
    0,
  );
}
