<script lang="ts">
import type { CatalogModel } from '../catalog/types.ts';
import { editableFields } from '../data/fakes.ts';
import { humanize } from '../data/format.ts';
import type { ViewField } from '../recipes/policy.ts';

interface SurfacePanelProps {
  /** Models to describe; a single model for a model page, all for a package. */
  models: CatalogModel[];
  /** Heading for the panel. */
  title?: string;
  /** Fields per model id, policy applied; defaults to every editable field. */
  fields?: Record<string, ViewField[]>;
}

let { models, title = 'What you get', fields }: SurfacePanelProps = $props();

function fieldsOf(model: CatalogModel): ViewField[] {
  return (
    fields?.[model.id] ??
    editableFields(model).map((f) => ({ ...f, label: humanize(f.name) }))
  );
}

const exposed = $derived(models.filter((m) => m.exposed));
</script>

<section class="panel" aria-label={title}>
  <h2>{title}</h2>
  <p class="lede">
    Everything below is generated by s-m-r-t from the model's decorator. None
    of it was written by hand.
  </p>

  {#each exposed as model (model.id)}
    <article>
      <h3>{model.name}</h3>
      <div class="grid">
        <div>
          <h4>Fields <span>{fieldsOf(model).length}</span></h4>
          <ul aria-label={`${model.name} fields`}>
            {#each fieldsOf(model) as field (field.name)}
              <li>
                <code>{field.name}</code>
                <span class="type">{field.type}{field.required ? ', required' : ''}</span>
              </li>
            {:else}
              <li class="none">None</li>
            {/each}
          </ul>
        </div>
        <div>
          <h4>REST routes <span>{model.rest.length}</span></h4>
          <ul>
            {#each model.rest as route (route.method + route.path)}
              <li><code><b>{route.method}</b> /api{route.path}</code></li>
            {:else}
              <li class="none">None</li>
            {/each}
          </ul>
        </div>
        <div>
          <h4>MCP tools <span>{model.mcp.length}</span></h4>
          <ul>
            {#each model.mcp as tool (tool.name)}
              <li><code>{tool.name}</code></li>
            {:else}
              <li class="none">None</li>
            {/each}
          </ul>
        </div>
        <div>
          <h4>CLI commands <span>{model.cli.length}</span></h4>
          <ul>
            {#each model.cli as command (command.name)}
              <li><code>{command.name}</code></li>
            {:else}
              <li class="none">None</li>
            {/each}
          </ul>
        </div>
        <div>
          <h4>
            Methods <span>{model.methods.filter((m) => m.aiCallable).length}</span>
            AI-callable
          </h4>
          <ul>
            {#each model.methods as method (method.name)}
              <li>
                <code>{method.name}({method.parameters.join(', ')})</code>
                {#if method.aiCallable}<mark>AI</mark>{/if}
              </li>
            {:else}
              <li class="none">None</li>
            {/each}
          </ul>
        </div>
      </div>
    </article>
  {:else}
    <p>This package exposes no generated REST, MCP or CLI surface.</p>
  {/each}
</section>

<style>
  .panel {
    display: grid;
    gap: var(--smrt-spacing-4);
  }

  h2,
  h3,
  h4,
  p {
    margin: 0;
  }

  .lede {
    color: var(--smrt-color-on-surface-variant);
  }

  article {
    display: grid;
    gap: var(--smrt-spacing-3);
    padding: var(--smrt-spacing-4);
    border: 1px solid var(--smrt-color-outline-variant);
    border-radius: var(--smrt-radius-large);
  }

  .grid {
    display: grid;
    gap: var(--smrt-spacing-4);
    grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
  }

  h4 {
    font-size: 0.9rem;
    color: var(--smrt-color-on-surface-variant);
  }

  h4 span {
    padding: 0 var(--smrt-spacing-2);
    border-radius: var(--smrt-radius-medium);
    background: var(--smrt-color-surface-variant);
  }

  ul {
    display: grid;
    gap: var(--smrt-spacing-1);
    margin: var(--smrt-spacing-2) 0 0;
    padding: 0;
    list-style: none;
  }

  code {
    font-size: 0.85rem;
    overflow-wrap: anywhere;
  }

  .none {
    color: var(--smrt-color-on-surface-variant);
  }

  .type {
    color: var(--smrt-color-on-surface-variant);
    font-size: 0.8rem;
  }

  mark {
    padding: 0 var(--smrt-spacing-1);
    border-radius: var(--smrt-radius-medium);
    background: var(--smrt-color-tertiary-container);
    color: var(--smrt-color-on-tertiary-container);
    font-size: 0.75rem;
  }
</style>
